workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
    scripts:
      - name: Get Flutter dependencies
        script: |
          set -e
          flutter doctor -v
          flutter pub get
          test -f ios/Flutter/Generated.xcconfig
      - name: Install CocoaPods
        script: |
          set -e
          cd ios
          pod install
      - name: Build iOS IPA
        script: |
          set -e
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - micheeglele@gmail.com
        notify:
          success: true
          failure: true
