class Strings {
  static const _fr = {
    'signup': 'Inscription',
    'signup_title': 'Inscription',
    'signup_subtitle': 'Crée ton compte, découvre les restos autour de toi et lance ton activité plus sereinement.',
    'firstname': 'Prénom',
    'lastname': 'Nom',
    'username': "Nom d'utilisateur",
    'username_or_email': "Nom d'utilisateur ou adresse mail",
    'email': 'Adresse mail',
    'phone_number': 'Numéro de téléphone',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'confirm_password_required': 'Veuillez confirmer votre mot de passe',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
    'terms_acceptance': 'Créer un compte signifie que vous acceptez nos conditions d\'utilisation et notre politique de confidentialité',
    'already_have_account': 'Vous avez déjà un compte ?',
    'login': 'Connexion',
    'login_title': 'Connexion',
    'login_subtitle': 'Retrouve ton espace, tes commandes et ton restaurant en quelques secondes.',
    'dont_have_account': "Vous n'avez pas encore de compte ?",
    'forgotten_password': 'Mot de passe oublié ?',
    'forgotten_password_title': 'Mot de passe oublié',
    'forgotten_password_subtitle': 'Saisissez votre adresse mail pour recevoir un code sécurisé.',
    'verify_email': "Vérifier l'adresse mail",
    'reset_code_sent': 'Un code de réinitialisation a été envoyé par email.',
    'reset_code_send_failed': "Impossible d'envoyer le code de réinitialisation.",
    'no_account_for_email': 'Aucun compte trouvé avec cet email.',
    'verification_code': 'Code de vérification',
    'verification_code_hint': 'Code à 6 chiffres',
    'verify_code': 'Vérifier le code',
    'invalid_or_expired_code': 'Code invalide ou expiré.',
    'reset_password_title': 'Réinitialiser le mot de passe',
    'reset_password_subtitle': 'Entrez le code reçu par email avant de choisir un nouveau mot de passe.',
    'new_password': 'Nouveau mot de passe',
    'reset_password': 'Réinitialiser le mot de passe',
    'same_password_error': 'Le nouveau mot de passe doit être différent de l\'ancien.',
    'user_not_found': 'Erreur : utilisateur introuvable.',
    'form_invalid': 'Veuillez remplir correctement les champs.',
    'password_updated': 'Votre mot de passe a bien été mis à jour.',
    'back_to_login': 'Retour à la connexion',
    'enter_firstname': 'Veuillez entrer le prénom',
    'enter_lastname': 'Veuillez entrer le nom',
    'enter_username': "Veuillez entrer le nom d'utilisateur",
    'enter_valid_email': 'Veuillez entrer une adresse mail valide',
    'enter_phone': 'Veuillez entrer un numéro',
    'phone_length': 'Le numéro doit contenir @count chiffres',
    'benin_phone_format': 'Utilisez le format 01 xx xx xx xx',
    'enter_password': 'Veuillez entrer un mot de passe',
    'min_4_chars': 'Veuillez entrer au moins 4 caractères',
    'min_6_chars': 'Veuillez entrer au moins 6 caractères',
    'max_13_chars': 'Maximum 13 caractères',
    'login_missing_fields': 'Erreur : entrez un login et un mot de passe',
    'login_failed': 'Erreur : identifiant(s) incorrect(s)',
    'internet_required': 'Connectez-vous à internet pour continuer',
    'splash_title': 'La cuisine de quartier, plus chaleureuse et plus simple.',
    'splash_subtitle': 'Découvrez, commandez et gérez vos micro-restaurants avec une expérience plus fluide.',
    'splash_loading': 'Préparation de votre expérience...',
    'onboarding_step_1_title': 'Découvrez les saveurs maison près de vous',
    'onboarding_step_1_body': 'Trouvez des repas généreux, des restaurants locaux et des plats adaptés à vos envies.',
    'onboarding_step_2_title': 'Commandez simplement, où que vous soyez',
    'onboarding_step_2_body': 'Parcourez les menus, suivez votre panier et retrouvez rapidement vos plats favoris.',
    'onboarding_step_3_title': 'Vendez vos plats en toute confiance',
    'onboarding_step_3_body': 'Créez votre espace restaurant, publiez vos plats et gérez les commandes depuis l\'app.',
    'skip': 'Passer',
    'next': 'Suivant',
    'start': 'Commencer',
  };

  static String of(String key, [Map<String, String>? params]) {
    var text = _fr[key] ?? key;
    if (params != null) {
      params.forEach((k, v) => text = text.replaceAll('@$k', v));
    }
    return text;
  }
}
